module.exports = {
    studyUploadError:{
        code:'10001',
        message:'文件上传失败',
        result:''
    },
    studyFindError:{
        code:'10002',
        message:'文件查询失败',
        result:''
    },
    studyDeleteError:{
        code:'10003',
        message:'文件删除异常',
        result:''
    },
    studyAlreadyDelete:{
        code:'10004',
        message:'要删除的文件不存在',
        result:''
    },
    imageUploadError:{
        code:'10101',
        message:'图片上传失败',
        result:''
    },
    imageFindError:{
        code:'10102',
        message:'图片查询失败',
        result:''
    },
    imageDeleteError:{
        code:'10103',
        message:'图片删除异常',
        result:''
    },
    imageAlreadyDelete:{
        code:'10104',
        message:'要删除的图片不存在',
        result:''
    },
    commentUploadError:{
        code:'10201',
        message:'留言上传失败',
        result:''
    },
    commentFindError:{
        code:'10202',
        message:'留言查询失败',
        result:''
    }
}